language: csharp
mono: none
dotnet: 3.1.201
dist: bionic
script:
  - mkdir tools
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
  - sudo apt-get install -y apt-transport-https aspnetcore-runtime-2.1
  - dotnet build -nologo -c Develop Gliep.Full.sln
  - dotnet test -nologo -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude="\"[xunit.*]*,[GeminiLab.Core2*]*\"" -p:ExcludeByAttribute="CompilerGeneratedAttribute" -v=minimal XUnitTester/XUnitTester.csproj
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - ./tools/csmacnz.Coveralls --opencover -i 'XUnitTester/coverage.opencover.xml' --treatUploadErrorsAsWarnings --useRelativePaths --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci"
  - cat meta/eg.gl
  - cat meta/eg.gl | dotnet run -p ./GliepDumper/GliepDumper.csproj -- -p
  - cat example.gl
  - cat example.gl | dotnet run -p ./GliepDumper/GliepDumper.csproj -- -a -u
  - dotnet run -p ./Gliep/Gliep.csproj -- ./meta/example/mandelbrot.gl
